### ISSUE TITLE
[problem ]mimosa watch --server 

### ISSUE THREAD

**Issue by raulghm** [breatheforks/mimosa-peepcode#3]
When run: sudo mimosa watch --server
Can't start server...

Unable to start Mimosa for the following reason(s):
- Cannot resolve location of testemSimple.configFile, [[ /Users/raulghm/Downloads/mimosa-peepcode-master/public/testem.json ]]

**Comment by dbashford** [comment]
If I clone the latest code, run `npm install` and the `mimosa watch -s`, I do not get that error.  Must be some mismatch between the current version up on github and the one you've got locally?

However, after the changes made after merging my PR something isn't working with the testem-simple integration.  Debugging...

**Comment by dbashford** [comment]
Broken tests seem to be swallowed for some reason.  Tests broken because of #3.

Need to figure out why they are swallowed though.

**Comment by dbashford** [comment]
If you do this...
- latest mimosa installed
- `git clone https://github.com/breathe/mimosa-peepcode`
- `cd mimosa-peepcode`
- `npm install`
- `mimosa build` , have to cntl-c after compilations because when tests fail it gets hung up.
- `npm install -g testem`
- `testem ci`

It might hang on you.  For some reason when tests are broken, `testem ci` is not exiting.  It gets stuck.

**Comment by raulghm** [comment]
Excelent, working :+1:

**Comment by dbashford** [comment]
Do the tests run?  Should see 6 of 6 successful.

**Comment by raulghm** [comment]
The Test have following errors:

not ok 1 PhantomJS 1.9 - Tables, Initial state: should redirect to '/tables' asynchronously
    ---
        message: "Setup failed on should redirect to '/tables' asynchronously: 'undefined' is not a function (evaluating 'this.merge(helpers, Ember.Handlebars.helpers)')"
    ...
not ok 2 PhantomJS 1.9 - Tables, Initial state: should display six tables asynchronously
    ---
        message: "asserting 0 equals 6"
    ...
not ok 3 PhantomJS 1.9 - Tables, Table 2: should display food menu with 5 choices and placeholder text asynchronously
    ---
        message: "asserting "" equals "2""
    ...

**Comment by dbashford** [comment]
If you upgrade handlebars to te latest on the handlebars website, both handlebars and handlebars-runtime, it'll be good.

**Comment by raulghm** [comment]
Nop, I got the same errors...

**Comment by dbashford** [comment]
If you upgrade and then just run `testem ci` it'll still not work.  Have to upgrade, then run `mimosa build` again.  Then `testem ci`.

**Comment by breathe** [comment]
One point -- invoking mimosa with sudo is probably not what you want to do I would think --  if I've got that in the readme I need to fix that ...

I made a change after merging the pull request from dbashford which might have introduced an error with testing -- but I'm travelling at the moment and not where I can check or fix...

I moved testrunner.html into the project's assets directory -- my goal  doing this was to try to find a way to  ensure that relative URL requests within the testem environment resolved in the same manner as they do in the live environment served by the project's express server...  Currently there doesn't seem to be a good builtin way to achieve that with testem so I had to relocate testrunner.html and use a trick with a testem route ...  This was working in my environment though ..

Regarding the handlebars errors - you have to precompile with handlebars 1.0.0 and emblem 0.3.0 -- running npm install in the project directory should bring the right versions of these libraries into the project -- is this not working on a new checkout of the project ..?

I'm on holiday this next week -- and amazingly was able to leave my laptop behind so I'm afraid I can't merge any fixes until I return ...

**Comment by dbashford** [comment]
There is a 3rd component to the compilation and that is Ember's Handlebars stuff.  It changed recently and is te likely culprit.

**Comment by dbashford** [comment]
so this should all be good now?

**Comment by airportyh** [comment]
I looked into this on the Testem side. It is hanging if the test throws because that causes `resume()` not to get called, and as a result the test suite doesn't end. This is a qunit specific issue. I am not sure if qunit has any facility to handle this case, and then signal the termination the test suite? If there is please enlighten me.

**Comment by dbashford** [comment]
Thx @airportyh, good to know.  After playing with this awhile, and seeing `testem` just spin and spin, I was beginning to assume this was going to be a test suite issue.  I've done quite a bit of testing with testem/mocha/chai and never seen that happen.

**Comment by raulghm** [comment]
Thanks @breathe and sorry the delay to respond, I just checked, the compilation and testing works well :)
